### ISSUE TITLE
Separate top netlist and top testbench netlist in FPGA Spice

### ISSUE THREAD

**Issue by egiacomin** [LNIS-Projects/OpenFPGA#5]
In FPGA SPice, when using the --print_top_testbench option, it creates a top testbench netlist which instantiates all the other components (SB, CB, CLBs, etc.) as well as the testbench components (measure commands, voltage sources, etc) in a single file.I would be cleaner to create two file:1- the top spice netlist of the FPGA, which simply instantiates all the other components (SB, CB, CLBs, etc.)2- the top spice tesbench netlist, which instantiate the top FPGA and the other testbench components.

**Comment by tangxifan** [comment]
Addressed in #87
