### ISSUE TITLE
SDC global ports constraints

### ISSUE THREAD

**Issue by egiacomin** [LNIS-Projects/OpenFPGA#50]
Hello,

1- In global_ports.sdc, some global ports are defined as clocks while they clearly should not:

*****
create_clock Reset[0]-period 10 -waveform {0 5} [list [get_ports { Reset[0]}]]
set_drive 0 Reset[0]
******

Assuming the reset is assynchronous, I would suggest:

set_false_path -from [get_ports { Reset[0]}]

2- I would suggest defining the clock following the "standard" syntax (as defined in the "Constraining Designs for Synthesis and Timing Analysis: A Practical Guide to Synopsys Design Constraints (SDC)" book for instance):
create_clock -name prog_clk[0] -period 100 -waveform {0 50} [get_ports {prog_clk[0]}]
Instead of
create_clock prog_clk[0]-period 100 -waveform {0 50}

Thanks,
Edouard

**Comment by tangxifan** [comment]
Should we still keep `set_drive 0`?

**Comment by egiacomin** [comment]
I would also remove those as it will be technology dependent, and will also depend on how the FPGA externally, so it should be added manually by the physical design engineers.
