### ISSUE TITLE
OpenFPGA Shell 

### ISSUE THREAD

**Issue by GunnerG** [LNIS-Projects/OpenFPGA#75]
1->I have successfully compiled the OpenFPGA project.
I want to access OpenFPGA Shell.
Do i need to setup environment variable to access this shell globally..?

**Comment by tangxifan** [comment]
Hello,
   OpenFPGA does not require any environment variables.

   If you want to try OpenFPGA shell, you can follow

```
   cd ${YOUR_OPENFPGA_ROOT_DIRECTORY}/openfpga
   ./openfpga
```
   
   The learning curve of OpenFPGA commands could be steep, therefore I suggest you follow our [quick tutorials](https://openfpga.readthedocs.io/en/master/tutorials/design_flow/blif_to_verification.html) first.
   Our task-run scripts can help you understand how OpenFPGA works.
