### ISSUE TITLE
Assertion "true == model_is_default(default_id)" is failed

### ISSUE THREAD

**Issue by buddynohair** [LNIS-Projects/OpenFPGA#78]
Hello,

sorry for the disturb again. I kinda have a new problem. 
I made a few changes in the k6_frac_N10_adder_chain_40nm_openfpga.xml. For example, i wrote a 8-to-1 multiplexer and used it in the connection box. In addition i changed the configuration protocol with a new customized D-Flipflop. 
After i ran it manually, i got the response: Assertion "true == model_is_default(default_id)" is failed

Would you give me any advice?
<img width="1280" alt="截屏2020-08-23下午2 32 12" src="https://user-images.githubusercontent.com/66943123/90978678-db247c80-e54f-11ea-9cdd-d4ab5aff5de2.png">

<img width="1280" alt="截屏2020-08-23下午2 55 14" src="https://user-images.githubusercontent.com/66943123/90978798-bbda1f00-e550-11ea-9db4-47550a86e775.png">
<img width="1280" alt="截屏2020-08-23下午1 42 41" src="https://user-images.githubusercontent.com/66943123/90978810-c5638700-e550-11ea-8b46-8d721843a674.png">

**Comment by buddynohair** [comment]
Hello,

yes for sure

[arch.zip](https://github.com/LNIS-Projects/OpenFPGA/files/5114671/arch.zip)
[task.log](https://github.com/LNIS-Projects/OpenFPGA/files/5114674/task.log)
[mux8to1.log](https://github.com/LNIS-Projects/OpenFPGA/files/5114675/mux8to1.log)
[d_ff.log](https://github.com/LNIS-Projects/OpenFPGA/files/5114676/d_ff.log)

**Comment by tangxifan** [comment]
Hello,
   I think you forgot to set the default model for you FFs in your architecture file.
   We expect you to tell OpenFPGA in each type of circuit model, what is the default one, through syntax `is_default`
   OpenFPGA can automatically link `pb_type` or other FPGA resources to default models when not specified in your architecture file.
   Anyway, some check codes are required to tell users that a default model is necessary. I will patch this.

**Comment by buddynohair** [comment]
Ah ok thank you very much .

**Comment by buddynohair** [comment]
Hello,

can you please have a look on another issue ? I think the source code is generated but there's a problem with test bench generation.
<img width="1280" alt="1" src="https://user-images.githubusercontent.com/66943123/91040389-7419cd00-e60e-11ea-921a-a2cf34b86a65.png">

[k6_frac_N10_adder_chain_mem16K_40nm.zip](https://github.com/LNIS-Projects/OpenFPGA/files/5117473/k6_frac_N10_adder_chain_mem16K_40nm.zip)

**Comment by tangxifan** [comment]
Hello,
   I checked your architecture file. You defined a new `ccff` circuit model called `d_ff`.
   The `ccff` is the flip-flop for programming circuitry. The clock signal of `ccff` should be a programming clock.
   However, you define it as a regular clock (XML syntax `is_prog` is set `false`).
   I do not know how you want to use the flip-flop.
   If it is part of programming circuitry, it should follow the `ccff` examples in your architecture file.
   If it is in the datapath, it should follow the `ff`` examples in your architecture file.
   Currently, it mixed the two.

**Comment by buddynohair** [comment]
Hello,
 
i have solved this problem. thank you very much !
